INSERT INTO artist (name) VALUES ("A Touch Of Brass Big Band");
INSERT INTO artist (name) VALUES ("Adam De La Halle");
INSERT INTO artist (name) VALUES ("Ahmad Jamal");
INSERT INTO artist (name) VALUES ("Al Molina");
INSERT INTO artist (name) VALUES ("Albert G. Sandoval, Jr., and Ray Winnie");
INSERT INTO artist (name) VALUES ("Alfred Brendel");
INSERT INTO artist (name) VALUES ("Andre Nickatina");
INSERT INTO artist (name) VALUES ("Angelo Badalamenti");
INSERT INTO artist (name) VALUES ("Anonymous");
INSERT INTO artist (name) VALUES ("Anthony Rooley: The Consort Of Musicke");
INSERT INTO artist (name) VALUES ("Antonio Vivaldi");
INSERT INTO artist (name) VALUES ("Aphex Twin");
INSERT INTO artist (name) VALUES ("Arcangelo Corelli");
INSERT INTO artist (name) VALUES ("Arlienne N. Williams");
INSERT INTO artist (name) VALUES ("Chief Dan George");
INSERT INTO artist (name) VALUES ("Louis Armstrong");
INSERT INTO artist (name) VALUES ("Duke Ellington");
INSERT INTO artist (name) VALUES ("Art Blakey");
INSERT INTO artist (name) VALUES ("Art Blakey & The Jazz Messengers");
INSERT INTO artist (name) VALUES ("Art Farmer");
INSERT INTO artist (name) VALUES ("Art Neville");
INSERT INTO artist (name) VALUES ("Art Pepper");
INSERT INTO artist (name) VALUES ("Art Tatum");
INSERT INTO artist (name) VALUES ("Asano Umewaka and Asano Sanae");
INSERT INTO artist (name) VALUES ("Atari Teenage Riot");
INSERT INTO artist (name) VALUES ("B.B. King");
INSERT INTO artist (name) VALUES ("Ivan Neville's Dumpstaphunk");
INSERT INTO artist (name) VALUES ("Bahamadia");
INSERT INTO artist (name) VALUES ("Beatriz Of Dia");
INSERT INTO artist (name) VALUES ("Ben Harper");
INSERT INTO artist (name) VALUES ("The Skatalites");
INSERT INTO artist (name) VALUES ("Bernard Haitink: Royal Concertgebouw Orchestra");
INSERT INTO artist (name) VALUES ("Big Chief Monk Boudreaux");
INSERT INTO artist (name) VALUES ("Galactic");
INSERT INTO artist (name) VALUES ("Bill Evans");
INSERT INTO artist (name) VALUES ("Jim Hall");
INSERT INTO artist (name) VALUES ("Bill Holman Band");
INSERT INTO artist (name) VALUES ("Billie Holiday");
INSERT INTO artist (name) VALUES ("Billy Strayhorn");
INSERT INTO artist (name) VALUES ("Billy Strayhorn Quintet");
INSERT INTO artist (name) VALUES ("Billy Strayhorn Sextet");
INSERT INTO artist (name) VALUES ("Billy Strayhorn Trio");
INSERT INTO artist (name) VALUES ("Bjork");
INSERT INTO artist (name) VALUES ("Bob Brookmeyer");
INSERT INTO artist (name) VALUES ("Bob Dylan");
INSERT INTO artist (name) VALUES ("Bob Mintzer");
INSERT INTO artist (name) VALUES ("Bob Mintzer Big Band");
INSERT INTO artist (name) VALUES ("Bobby McFerrin");
INSERT INTO artist (name) VALUES ("Bobby Shew Quintet");
INSERT INTO artist (name) VALUES ("Bonnie Raitt");
INSERT INTO artist (name) VALUES ("Jon Cleary");
INSERT INTO artist (name) VALUES ("Brad Mehldau");
INSERT INTO artist (name) VALUES ("Bruce Hornsby");
INSERT INTO artist (name) VALUES ("Bud Powell");
INSERT INTO artist (name) VALUES ("Caetano Veloso");
INSERT INTO artist (name) VALUES ("Carl Saunders");
INSERT INTO artist (name) VALUES ("Celia Cruz");
INSERT INTO artist (name) VALUES ("Charles Dutoit");
INSERT INTO artist (name) VALUES ("Montreal Symphony Orchestra");
INSERT INTO artist (name) VALUES ("Charles Ives");
INSERT INTO artist (name) VALUES ("Charlie Parker");
INSERT INTO artist (name) VALUES ("Dizzy Gillespie");
INSERT INTO artist (name) VALUES ("Richard Cheese");
INSERT INTO artist (name) VALUES ("Cheo Feliciano");
INSERT INTO artist (name) VALUES ("Chet Baker");
INSERT INTO artist (name) VALUES ("Chet Baker & Art Pepper");
INSERT INTO artist (name) VALUES ("Chick Corea");
INSERT INTO artist (name) VALUES ("Chico Buarque");
INSERT INTO artist (name) VALUES ("Chinle Galileans");
INSERT INTO artist (name) VALUES ("Christian Lindberg");
INSERT INTO artist (name) VALUES ("Roland Paintinen");
INSERT INTO artist (name) VALUES ("Claude Debussy");
INSERT INTO artist (name) VALUES ("Claudio Arrau");
INSERT INTO artist (name) VALUES ("Claudio Monteverdi");
INSERT INTO artist (name) VALUES ("Clifford Brown");
INSERT INTO artist (name) VALUES ("Jay Jay Johnson");
INSERT INTO artist (name) VALUES ("Jimmy Heath");
INSERT INTO artist (name) VALUES ("John Lewis");
INSERT INTO artist (name) VALUES ("Percy Heath");
INSERT INTO artist (name) VALUES ("Kenny Clarke");
INSERT INTO artist (name) VALUES ("Max Roach");
INSERT INTO artist (name) VALUES ("Max Roach Quintet");
INSERT INTO artist (name) VALUES ("Colin Davis");
INSERT INTO artist (name) VALUES ("Staatskapelle Dresden");
INSERT INTO artist (name) VALUES ("Conrad Herwig");
INSERT INTO artist (name) VALUES ("Tim Hagans");
INSERT INTO artist (name) VALUES ("Ben Schachter");
INSERT INTO artist (name) VALUES ("David Kikoski");
INSERT INTO artist (name) VALUES ("James Genus");
INSERT INTO artist (name) VALUES ("Jeff Tain Watts");
INSERT INTO artist (name) VALUES ("Corinne Bailey Rae");
INSERT INTO artist (name) VALUES ("Count Basie");
INSERT INTO artist (name) VALUES ("Count Basie & His Orchestra");
INSERT INTO artist (name) VALUES ("Dave Edmunds");
INSERT INTO artist (name) VALUES ("Dave Eshelman's Jazz Garden Big Band");
INSERT INTO artist (name) VALUES ("Dave Holland Big Band");
INSERT INTO artist (name) VALUES ("Dave Holland Quintet");
INSERT INTO artist (name) VALUES ("Dave Holland Sextet");
INSERT INTO artist (name) VALUES ("Dave Tarras");
INSERT INTO artist (name) VALUES ("David Bowie");
INSERT INTO artist (name) VALUES ("David Hill");
INSERT INTO artist (name) VALUES ("Westminster Cathedral Choir");
INSERT INTO artist (name) VALUES ("Diana Krall");
INSERT INTO artist (name) VALUES ("Dietrich Buxtehude");
INSERT INTO artist (name) VALUES ("Djavan");
INSERT INTO artist (name) VALUES ("Dominique Visse: Ensemble Claument Janequin, Ensemble Les Elements");
INSERT INTO artist (name) VALUES ("Don Caesar Muquinche (of Ecuador)");
INSERT INTO artist (name) VALUES ("Donald Harrison Jr");
INSERT INTO artist (name) VALUES ("The Tipitina's Interns");
INSERT INTO artist (name) VALUES ("Dori Caymmi");
INSERT INTO artist (name) VALUES ("Dr. John");
INSERT INTO artist (name) VALUES ("Dubravka Tom");
INSERT INTO artist (name) VALUES ("Edgard Varase");
INSERT INTO artist (name) VALUES ("Edie Brickell");
INSERT INTO artist (name) VALUES ("Jerry Garcia");
INSERT INTO artist (name) VALUES ("Rob Wasserman");
INSERT INTO artist (name) VALUES ("Edu Lobo");
INSERT INTO artist (name) VALUES ("Efrae­n, Quichua harpist of Cotacachi, Ecuador");
INSERT INTO artist (name) VALUES ("El Gran Combo");
INSERT INTO artist (name) VALUES ("Elgar Howarth: London Sinfonietta");
INSERT INTO artist (name) VALUES ("Eliane Elias");
INSERT INTO artist (name) VALUES ("Elisabeta Pavel");
INSERT INTO artist (name) VALUES ("Ella Fitzgerald");
INSERT INTO artist (name) VALUES ("Elton John");
INSERT INTO artist (name) VALUES ("Elvis Costello");
INSERT INTO artist (name) VALUES ("Marc Ribot");
INSERT INTO artist (name) VALUES ("Emilio De Cavalieri");
INSERT INTO artist (name) VALUES ("Erich Leinsdorf");
INSERT INTO artist (name) VALUES ("Ernestine Anderson");
INSERT INTO artist (name) VALUES ("George Shearing");
INSERT INTO artist (name) VALUES ("Euripides");
INSERT INTO artist (name) VALUES ("Europe");
INSERT INTO artist (name) VALUES ("Fabia¡n & Eleuterio Congo (of Ecuador)");
INSERT INTO artist (name) VALUES ("Fania All-Stars");
INSERT INTO artist (name) VALUES ("Fellowship Independant Baptist Church Congregation (Stanley, VA)");
INSERT INTO artist (name) VALUES ("Fenders");
INSERT INTO artist (name) VALUES ("Foster The People");
INSERT INTO artist (name) VALUES ("Francois Couperin");
INSERT INTO artist (name) VALUES ("Frank Foster");
INSERT INTO artist (name) VALUES ("Frank Wess");
INSERT INTO artist (name) VALUES ("Frank Mantooth");
INSERT INTO artist (name) VALUES ("Frank Rosolino");
INSERT INTO artist (name) VALUES ("Frank Sinatra with Count Basie");
INSERT INTO artist (name) VALUES ("Frankie Ruiz");
INSERT INTO artist (name) VALUES ("Franz Joseph Haydn");
INSERT INTO artist (name) VALUES ("Franz Schubert");
INSERT INTO artist (name) VALUES ("Fred Wesley");
INSERT INTO artist (name) VALUES ("Freddie Hubbard");
INSERT INTO artist (name) VALUES ("Woody Shaw");
INSERT INTO artist (name) VALUES ("Fritz Wunderlich");
INSERT INTO artist (name) VALUES ("Hubert Giesen");
INSERT INTO artist (name) VALUES ("G.P. Saraswathi");
INSERT INTO artist (name) VALUES ("George Crumb");
INSERT INTO artist (name) VALUES ("George Frideric Handel");
INSERT INTO artist (name) VALUES ("George Gershwin");
INSERT INTO artist (name) VALUES ("George Mitchell");
INSERT INTO artist (name) VALUES ("Kaya David");
INSERT INTO artist (name) VALUES ("Gerry Mulligan");
INSERT INTO artist (name) VALUES ("Gheorghe Motoi");
INSERT INTO artist (name) VALUES ("Gidon Kremer");
INSERT INTO artist (name) VALUES ("Boston Symphony Orchestra");
INSERT INTO artist (name) VALUES ("Gil Evans");
INSERT INTO artist (name) VALUES ("Gilberto Gil");
INSERT INTO artist (name) VALUES ("Gilberto Santa Rosa");
INSERT INTO artist (name) VALUES ("Giovanni Gabrieli");
INSERT INTO artist (name) VALUES ("Giovanni Legrenzi");
INSERT INTO artist (name) VALUES ("Giovanni Pierluigi Da Palestrina");
INSERT INTO artist (name) VALUES ("Giulio Caccini");
INSERT INTO artist (name) VALUES ("Giuseppe Verdi");
INSERT INTO artist (name) VALUES ("Global Jazz Orchestra");
INSERT INTO artist (name) VALUES ("Gordon Goodwin's Big Phat Band");
INSERT INTO artist (name) VALUES ("Gran Afro Cuban Orquesta De Generoso Jimenez");
INSERT INTO artist (name) VALUES ("Grant Green");
INSERT INTO artist (name) VALUES ("Jimmy Smith");
INSERT INTO artist (name) VALUES ("Gregorian Chant");
INSERT INTO artist (name) VALUES ("Grupo Niche");
INSERT INTO artist (name) VALUES ("Guillaume De Machaut");
INSERT INTO artist (name) VALUES ("Guillaume Dufay");
INSERT INTO artist (name) VALUES ("Guruh Gipsy");
INSERT INTO artist (name) VALUES ("Gypsy Children from Gistesti, Rumania");
INSERT INTO artist (name) VALUES ("Hector Lavoe");
INSERT INTO artist (name) VALUES ("Hank Mobley");
INSERT INTO artist (name) VALUES ("Hans Sachs");
INSERT INTO artist (name) VALUES ("Henry Purcell");
INSERT INTO artist (name) VALUES ("George Porter, Jr.");
INSERT INTO artist (name) VALUES ("Zigaboo Modeliste");
INSERT INTO artist (name) VALUES ("Renard Poche");
INSERT INTO artist (name) VALUES ("Michael Brecker");
INSERT INTO artist (name) VALUES ("Roy Hargrove");
INSERT INTO artist (name) VALUES ("Hildegard Von Bingen");
INSERT INTO artist (name) VALUES ("Horace Silver");
INSERT INTO artist (name) VALUES ("I-Doser");
INSERT INTO artist (name) VALUES ("Irma Thomas & Marcia Ball");
INSERT INTO artist (name) VALUES ("Ishida Ishimatsu");
INSERT INTO artist (name) VALUES ("Ivan Lins");
INSERT INTO artist (name) VALUES ("Joe Pass");
INSERT INTO artist (name) VALUES ("Jack Kevorkian");
INSERT INTO artist (name) VALUES ("Jack Wilkins");
INSERT INTO artist (name) VALUES ("Jackie McLean");
INSERT INTO artist (name) VALUES ("Jacopo Peri");
INSERT INTO artist (name) VALUES ("James Moody");
INSERT INTO artist (name) VALUES ("Jamey Aebersold");
INSERT INTO artist (name) VALUES ("Jean-Philippe Rameau");
INSERT INTO artist (name) VALUES ("Jean-Pierre Armengaud");
INSERT INTO artist (name) VALUES ("Jello Biafra");
INSERT INTO artist (name) VALUES ("Jery Coker");
INSERT INTO artist (name) VALUES ("Jim McNeely");
INSERT INTO artist (name) VALUES ("Jimmy Bosch");
INSERT INTO artist (name) VALUES ("Wes Montgomery");
INSERT INTO artist (name) VALUES ("Joao Bosco");
INSERT INTO artist (name) VALUES ("Joe Henderson");
INSERT INTO artist (name) VALUES ("Joe Lovano");
INSERT INTO artist (name) VALUES ("Johann Sebastian Bach");
INSERT INTO artist (name) VALUES ("John Coltrane");
INSERT INTO artist (name) VALUES ("Johnny Hartman");
INSERT INTO artist (name) VALUES ("Paul Chambers");
INSERT INTO artist (name) VALUES ("John Hollenbeck");
INSERT INTO artist (name) VALUES ("John Hollenbeck Large Ensemble");
INSERT INTO artist (name) VALUES ("John Lennon");
INSERT INTO artist (name) VALUES ("John Lewis/Bill Perkins");
INSERT INTO artist (name) VALUES ("Johnny Pate And Orchestra And Wes Montgomery");
INSERT INTO artist (name) VALUES ("Johnny Smith");
INSERT INTO artist (name) VALUES ("Jose 'El Canario' Alberto");
INSERT INTO artist (name) VALUES ("Joshua Buck");
INSERT INTO artist (name) VALUES ("Simeon Gibbon");
INSERT INTO artist (name) VALUES ("Josquin Desprez");
INSERT INTO artist (name) VALUES ("Kanda Fukumaru");
INSERT INTO artist (name) VALUES ("Kawase Junsuke");
INSERT INTO artist (name) VALUES ("Keith Jarrett");
INSERT INTO artist (name) VALUES ("Keith Jarrett Trio");
INSERT INTO artist (name) VALUES ("Kenny Burrell");
INSERT INTO artist (name) VALUES ("Kenny Dorham");
INSERT INTO artist (name) VALUES ("Kenny Garrett");
INSERT INTO artist (name) VALUES ("Ki Suparman's Gamelon Group, Central Java, Indonesia");
INSERT INTO artist (name) VALUES ("Kiri Te Kanawa");
INSERT INTO artist (name) VALUES ("Jose Carreras");
INSERT INTO artist (name) VALUES ("Leonard Bernstein: West Side Story Pit Orchestra");
INSERT INTO artist (name) VALUES ("Kurt Elling");
INSERT INTO artist (name) VALUES ("Kwasi Badu with the UCLA Drum Ensemble");
INSERT INTO artist (name) VALUES ("La India, Eddie Palmieri");
INSERT INTO artist (name) VALUES ("Lanaiditsa");
INSERT INTO artist (name) VALUES ("Laurindo Almeida");
INSERT INTO artist (name) VALUES ("Lazy Bill Lucas Trio");
INSERT INTO artist (name) VALUES ("Lee Morgan");
INSERT INTO artist (name) VALUES ("Lee Ritenour");
INSERT INTO artist (name) VALUES ("Leningrad Dixieland Band");
INSERT INTO artist (name) VALUES ("Lenny Kravitz");
INSERT INTO artist (name) VALUES ("Rebirth Brass Band");
INSERT INTO artist (name) VALUES ("Troy 'Trombone Shorty' Andrews");
INSERT INTO artist (name) VALUES ("Pee Wee Ellis");
INSERT INTO artist (name) VALUES ("Maceo Parker");
INSERT INTO artist (name) VALUES ("Leonard Bernstein");
INSERT INTO artist (name) VALUES ("Lewis Black");
INSERT INTO artist (name) VALUES ("Lionheart");
INSERT INTO artist (name) VALUES ("Little Milton");
INSERT INTO artist (name) VALUES ("Los Lobos");
INSERT INTO artist (name) VALUES ("Lou Donaldson");
INSERT INTO artist (name) VALUES ("Louie Rami­rez");
INSERT INTO artist (name) VALUES ("Ray De La Paz");
INSERT INTO artist (name) VALUES ("Lucinda Williams");
INSERT INTO artist (name) VALUES ("Luiz Bonfe¡");
INSERT INTO artist (name) VALUES ("Magister Albertus");
INSERT INTO artist (name) VALUES ("Malcolm Bilson");
INSERT INTO artist (name) VALUES ("John Eliot Gardiner");
INSERT INTO artist (name) VALUES ("English Baroque Soloists");
INSERT INTO artist (name) VALUES ("Marc Anthony");
INSERT INTO artist (name) VALUES ("Marc Broussard");
INSERT INTO artist (name) VALUES ("Sam Bush");
INSERT INTO artist (name) VALUES ("Maria Schneider Jazz Orchestra");
INSERT INTO artist (name) VALUES ("Mariam Nirenberg");
INSERT INTO artist (name) VALUES ("Marian McPartland");
INSERT INTO artist (name) VALUES ("Martin Best Medieval Ensemble");
INSERT INTO artist (name) VALUES ("Mayoro Flute and Drumm Ensemble");
INSERT INTO artist (name) VALUES ("McCoy Tyner");
INSERT INTO artist (name) VALUES ("Michael Davis");
INSERT INTO artist (name) VALUES ("Mighty Sam McClain");
INSERT INTO artist (name) VALUES ("Reverend Raven and his Chain-Smoking Altar Boys");
INSERT INTO artist (name) VALUES ("Miles Davis");
INSERT INTO artist (name) VALUES ("Milt Jackson");
INSERT INTO artist (name) VALUES ("Milton Nascimento");
INSERT INTO artist (name) VALUES ("Mirella Freni");
INSERT INTO artist (name) VALUES ("Modest Mussorgsky");
INSERT INTO artist (name) VALUES ("National Symphony Orchestra Of The Ukraine & Theodore Kuchar");
INSERT INTO artist (name) VALUES ("Monterey Jazz Festival 50th Anniversary All-Stars");
INSERT INTO artist (name) VALUES ("Navajo Native Americans with Dinet Tsosie, leader");
INSERT INTO artist (name) VALUES ("Navajo Native Americans with Sandoval Begay, leader");
INSERT INTO artist (name) VALUES ("Neil Young");
INSERT INTO artist (name) VALUES ("Neville Marriner: Academy Of St. Martin In The Fields");
INSERT INTO artist (name) VALUES ("New Bethel Baptist Church Congregation (Detroit, MI)");
INSERT INTO artist (name) VALUES ("Norah Jones");
INSERT INTO artist (name) VALUES ("North Texas Jazz");
INSERT INTO artist (name) VALUES ("Nyakrom Brass Band");
INSERT INTO artist (name) VALUES ("Olu Dara and The Natchezippi Band feat. Donald Harrison, Jr.");
INSERT INTO artist (name) VALUES ("One O'Clock Lab Band");
INSERT INTO artist (name) VALUES ("One String Sam");
INSERT INTO artist (name) VALUES ("Orquesta De La Luz");
INSERT INTO artist (name) VALUES ("Orquesta GuayacÃ¡n");
INSERT INTO artist (name) VALUES ("Oscar Castro-Neves");
INSERT INTO artist (name) VALUES ("Oscar D'Leon");
INSERT INTO artist (name) VALUES ("Oscar Peterson");
INSERT INTO artist (name) VALUES ("Benny Green");
INSERT INTO artist (name) VALUES ("Ray Brown");
INSERT INTO artist (name) VALUES ("Gregory Hutchinson");
INSERT INTO artist (name) VALUES ("P. Susheela");
INSERT INTO artist (name) VALUES ("T. M. Soundararajan");
INSERT INTO artist (name) VALUES ("P. B. Sreenivos");
INSERT INTO artist (name) VALUES ("L. R. Eswari");
INSERT INTO artist (name) VALUES ("Parotin");
INSERT INTO artist (name) VALUES ("Paco Navarro");
INSERT INTO artist (name) VALUES ("Pat Martino");
INSERT INTO artist (name) VALUES ("Pat Metheny Group");
INSERT INTO artist (name) VALUES ("Pat Metheny");
INSERT INTO artist (name) VALUES ("Dave Holland");
INSERT INTO artist (name) VALUES ("Roy Haynes");
INSERT INTO artist (name) VALUES ("Paul McCartney");
INSERT INTO artist (name) VALUES ("Allen Toussaint");
INSERT INTO artist (name) VALUES ("Peter Phillips: The Tallis Scholars");
INSERT INTO artist (name) VALUES ("Philippe De Vitry");
INSERT INTO artist (name) VALUES ("Poncho Sanchez");
INSERT INTO artist (name) VALUES ("Preservation Hall Jazz Band");
INSERT INTO artist (name) VALUES ("Walter 'Wolfman' Washington");
INSERT INTO artist (name) VALUES ("Theresa Andersson");
INSERT INTO artist (name) VALUES ("Primus");
INSERT INTO artist (name) VALUES ("Prisoners At Mississippi State Penitentiary");
INSERT INTO artist (name) VALUES ("Radiohead");
INSERT INTO artist (name) VALUES ("Ramachandra Iyer");
INSERT INTO artist (name) VALUES ("Ravindran Iyer");
INSERT INTO artist (name) VALUES ("David Reck");
INSERT INTO artist (name) VALUES ("David Nelson");
INSERT INTO artist (name) VALUES ("Randy Newman");
INSERT INTO artist (name) VALUES ("Ray Brown Trio");
INSERT INTO artist (name) VALUES ("Rebecca Coupe Franks");
INSERT INTO artist (name) VALUES ("Rhoma Irama & His Soneta Group");
INSERT INTO artist (name) VALUES ("Richard Van Allan");
INSERT INTO artist (name) VALUES ("Colin Davis: Royal Opera House Orchestra & Chorus");
INSERT INTO artist (name) VALUES ("Richard Wagner");
INSERT INTO artist (name) VALUES ("Richie Beirach");
INSERT INTO artist (name) VALUES ("Robbie Robertson & Galactic");
INSERT INTO artist (name) VALUES ("Robert Cray Band");
INSERT INTO artist (name) VALUES ("Robert Plant & Lil Band O' Gold");
INSERT INTO artist (name) VALUES ("Robert Plant and The Soweto Gospel Choir");
INSERT INTO artist (name) VALUES ("Robert Schumann");
INSERT INTO artist (name) VALUES ("Ron McClure");
INSERT INTO artist (name) VALUES ("Ruphay (of Bolivia)");
INSERT INTO artist (name) VALUES ("Russ Freeman & Chet Baker");
INSERT INTO artist (name) VALUES ("Salieri");
INSERT INTO artist (name) VALUES ("Sergio, Quichua harpist of Cotacachi, Ecuador");
INSERT INTO artist (name) VALUES ("Shitaya Kotsura");
INSERT INTO artist (name) VALUES ("Shorty Rogers & His Giants");
INSERT INTO artist (name) VALUES ("Sigur Ros");
INSERT INTO artist (name) VALUES ("Slide Hampton");
INSERT INTO artist (name) VALUES ("Slide Hampton & The World Of Trombones");
INSERT INTO artist (name) VALUES ("Slide Hampton Quintet");
INSERT INTO artist (name) VALUES ("Sonny Rollins");
INSERT INTO artist (name) VALUES ("Coleman Hawkins");
INSERT INTO artist (name) VALUES ("Bob Cranshaw");
INSERT INTO artist (name) VALUES ("Mickey Roker");
INSERT INTO artist (name) VALUES ("Sonny Stitt");
INSERT INTO artist (name) VALUES ("Sonora Ponceta");
INSERT INTO artist (name) VALUES ("Stan Getz");
INSERT INTO artist (name) VALUES ("Stan Kenton");
INSERT INTO artist (name) VALUES ("Stan Kenton & His Orchestra");
INSERT INTO artist (name) VALUES ("Stanley Turrentine");
INSERT INTO artist (name) VALUES ("Steve Masakowski");
INSERT INTO artist (name) VALUES ("Steve Reich");
INSERT INTO artist (name) VALUES ("Steve Swallow");
INSERT INTO artist (name) VALUES ("Steve Turre");
INSERT INTO artist (name) VALUES ("Straight Outta Junior High");
INSERT INTO artist (name) VALUES ("Taj Mahal & The New Orleans Social Club");
INSERT INTO artist (name) VALUES ("Thad Jones");
INSERT INTO artist (name) VALUES ("Thad Jones & Mel Lewis");
INSERT INTO artist (name) VALUES ("The Beatles");
INSERT INTO artist (name) VALUES ("The Dave Brubeck Quartet");
INSERT INTO artist (name) VALUES ("The Decemberists");
INSERT INTO artist (name) VALUES ("The Dirty Dozen Brass Band with Joss Stone and Buddy Guy");
INSERT INTO artist (name) VALUES ("The Fieldstones");
INSERT INTO artist (name) VALUES ("The Flaming Lips");
INSERT INTO artist (name) VALUES ("The Gil Evans Orchestra");
INSERT INTO artist (name) VALUES ("The Hilliard Ensemble");
INSERT INTO artist (name) VALUES ("The Killers");
INSERT INTO artist (name) VALUES ("The Modern Jazz Quartet");
INSERT INTO artist (name) VALUES ("The Stan Getz Quartet");
INSERT INTO artist (name) VALUES ("The Tom 'Bones' Malone Jazz Septet");
INSERT INTO artist (name) VALUES ("Thelonious Monk");
INSERT INTO artist (name) VALUES ("Thelonious Monk Quartet With John Coltrane");
INSERT INTO artist (name) VALUES ("Thievery Corporation");
INSERT INTO artist (name) VALUES ("Thomas Binkley: Das Studio der fruhen Musik, Munchen");
INSERT INTO artist (name) VALUES ("Thomas Weelkes");
INSERT INTO artist (name) VALUES ("Tito Nieves");
INSERT INTO artist (name) VALUES ("Tito Puente");
INSERT INTO artist (name) VALUES ("Tito Puente & Domingo Quiazones");
INSERT INTO artist (name) VALUES ("Tito Puente & Tony Vega");
INSERT INTO artist (name) VALUES ("Tom Petty & The Heartbreakers");
INSERT INTO artist (name) VALUES ("Toma¡s Luis De Victoria");
INSERT INTO artist (name) VALUES ("Toots & The Maytals");
INSERT INTO artist (name) VALUES ("Toots Thielemans");
INSERT INTO artist (name) VALUES ("Toots Thielemans & Kenny Werner");
INSERT INTO artist (name) VALUES ("Toshiko Akiyoshi");
INSERT INTO artist (name) VALUES ("Toshiko Akiyoshi Big Band");
INSERT INTO artist (name) VALUES ("Trevor Pinnock: The English Concert");
INSERT INTO artist (name) VALUES ("Tukang Ginting & his group, Karo Batak Highlands, North Sumatra, Indonesia");
INSERT INTO artist (name) VALUES ("U2");
INSERT INTO artist (name) VALUES ("Ueno ShachÅ«");
INSERT INTO artist (name) VALUES ("unidentified (Joropo dance style of Venezuela)");
INSERT INTO artist (name) VALUES ("unidentified (mother of Cotacachi, Ecuador)");
INSERT INTO artist (name) VALUES ("unidentified Hungarian 52-year-old swineherded from Somogy County");
INSERT INTO artist (name) VALUES ("unidentified musicians from Pliatan, Bali, Indonesia");
INSERT INTO artist (name) VALUES ("unidentified musicians Ngudya Wirama Gamelan Group in Yogyakarta, Central Java, Indonesia");
INSERT INTO artist (name) VALUES ("unidentified musicians with the Royal Palace in Yogyakarta, Central Java, Indonesia");
INSERT INTO artist (name) VALUES ("unidentified percussion and wind orch. from Trichur, Kerala, India");
INSERT INTO artist (name) VALUES ("unidentified Quichua musicians of Cotacachi, Ecuador");
INSERT INTO artist (name) VALUES ("unidentified Quichua-speaking shaman of the jungle lowlands of eastern Ecuador");
INSERT INTO artist (name) VALUES ("University Of North Texas One O'Clock Lab Band");
INSERT INTO artist (name) VALUES ("unknown (traditional music from Bosnia and Hercegovina)");
INSERT INTO artist (name) VALUES ("unknown Ghanan Postal Workers");
INSERT INTO artist (name) VALUES ("unknown Rumanians from Borlovenii, Rumania");
INSERT INTO artist (name) VALUES ("unknown Russians from Varzuga, USSR");
INSERT INTO artist (name) VALUES ("unknown Sioux Native Americans");
INSERT INTO artist (name) VALUES ("unknown Ugandan Musicians");
INSERT INTO artist (name) VALUES ("Various Artists");
INSERT INTO artist (name) VALUES ("Victor Jara (of Chile)");
INSERT INTO artist (name) VALUES ("Vladimir Ashkenazy");
INSERT INTO artist (name) VALUES ("Vladimir Ashkenazy: Royal Philharmonic Orchestra");
INSERT INTO artist (name) VALUES ("Washington/ Bassman");
INSERT INTO artist (name) VALUES ("Wayne Shorter");
INSERT INTO artist (name) VALUES ("Wayne Shorter Quartet");
INSERT INTO artist (name) VALUES ("William Byrd");
INSERT INTO artist (name) VALUES ("William Cornysh");
INSERT INTO artist (name) VALUES ("William Steinberg: Boston Symphony Orchestra");
INSERT INTO artist (name) VALUES ("Willie ColÃ³n & RubÃ©n Blades");
INSERT INTO artist (name) VALUES ("Willie Nelson");
INSERT INTO artist (name) VALUES ("Wizlau von Ruegen");
INSERT INTO artist (name) VALUES ("Wolfgang Amadeus Mozart");
INSERT INTO artist (name) VALUES ("Woody Herman Orchestra");
INSERT INTO artist (name) VALUES ("Wynton Marsalis & Lincoln Center Jazz Orchestra");
INSERT INTO artist (name) VALUES ("Yes & The London Philharmonic");
INSERT INTO artist (name) VALUES ("(blank)");
INSERT INTO artist (name) VALUES ("Unknown");
INSERT INTO artist (name) VALUES ("Various");
