INSERT INTO composer (first_name, last_name) VALUES ("A.","Clayton");
INSERT INTO composer (first_name, last_name) VALUES ("A.","Harrison");
INSERT INTO composer (first_name, last_name) VALUES ("Aaron","Copland");
INSERT INTO composer (first_name, last_name) VALUES ("Ahmad","Jamal");
INSERT INTO composer (first_name, last_name) VALUES ("Al","Dubin");
INSERT INTO composer (first_name, last_name) VALUES ("Alain","Bergman");
INSERT INTO composer (first_name, last_name) VALUES ("Alan","Baylock");
INSERT INTO composer (first_name, last_name) VALUES ("Alan","Bergman");
INSERT INTO composer (first_name, last_name) VALUES ("Albany","Bigard");
INSERT INTO composer (first_name, last_name) VALUES ("Alberto","Dominguez");
INSERT INTO composer (first_name, last_name) VALUES ("Alex","North");
INSERT INTO composer (first_name, last_name) VALUES ("Andy","Leverne");
INSERT INTO composer (first_name, last_name) VALUES ("Andy","Razaf");
INSERT INTO composer (first_name, last_name) VALUES ("Angelo","Badalamenti");
INSERT INTO composer (first_name, last_name) VALUES ("Ann","Ronell");
INSERT INTO composer (first_name, last_name) VALUES ("Antonio Carlos","Jobim");
INSERT INTO composer (first_name, last_name) VALUES ("Antonio","Maria");
INSERT INTO composer (first_name, last_name) VALUES ("Arcangelo","Corelli");
INSERT INTO composer (first_name, last_name) VALUES ("Arlen","Harold");
INSERT INTO composer (first_name, last_name) VALUES ("Art","Tatum");
INSERT INTO composer (first_name, last_name) VALUES ("Arthur","Freed");
INSERT INTO composer (first_name, last_name) VALUES ("Arthur","Herzog");
INSERT INTO composer (first_name, last_name) VALUES ("Arthur","Johnston");
INSERT INTO composer (first_name, last_name) VALUES ("Arthur","Schwartz");
INSERT INTO composer (first_name, last_name) VALUES ("B.","Bernier");
INSERT INTO composer (first_name, last_name) VALUES ("Bob","Dylan");
INSERT INTO composer (first_name, last_name) VALUES ("B.","Freeman");
INSERT INTO composer (first_name, last_name) VALUES ("B.","Lane");
INSERT INTO composer (first_name, last_name) VALUES ("B.","Petkere");
INSERT INTO composer (first_name, last_name) VALUES ("B.","Russell");
INSERT INTO composer (first_name, last_name) VALUES ("B.","White");
INSERT INTO composer (first_name, last_name) VALUES ("B.G.","Sylva");
INSERT INTO composer (first_name, last_name) VALUES ("Bart","Howard");
INSERT INTO composer (first_name, last_name) VALUES ("","Bearden");
INSERT INTO composer (first_name, last_name) VALUES ("Bela","Bartok");
INSERT INTO composer (first_name, last_name) VALUES ("Ben","Jaffe");
INSERT INTO composer (first_name, last_name) VALUES ("Ben","Oakland");
INSERT INTO composer (first_name, last_name) VALUES ("Benny","Carter");
INSERT INTO composer (first_name, last_name) VALUES ("Benny","Golson");
INSERT INTO composer (first_name, last_name) VALUES ("Benny","Goodman");
INSERT INTO composer (first_name, last_name) VALUES ("Bernard","D. Hanighen");
INSERT INTO composer (first_name, last_name) VALUES ("Bernard","Hanighen");
INSERT INTO composer (first_name, last_name) VALUES ("Bernart","De Ventadorn");
INSERT INTO composer (first_name, last_name) VALUES ("Bernice","Petkere");
INSERT INTO composer (first_name, last_name) VALUES ("Bert","Kalmar");
INSERT INTO composer (first_name, last_name) VALUES ("Bert","Reisfeld");
INSERT INTO composer (first_name, last_name) VALUES ("Bertolt","Brecht");
INSERT INTO composer (first_name, last_name) VALUES ("Biff","Rose");
INSERT INTO composer (first_name, last_name) VALUES ("Bill","Bruford");
INSERT INTO composer (first_name, last_name) VALUES ("Bill","Evans");
INSERT INTO composer (first_name, last_name) VALUES ("Bill","Holman");
INSERT INTO composer (first_name, last_name) VALUES ("Bill","Russo");
INSERT INTO composer (first_name, last_name) VALUES ("Billie","Holiday");
INSERT INTO composer (first_name, last_name) VALUES ("Billy","Rose");
INSERT INTO composer (first_name, last_name) VALUES ("Billy","Strayhorn");
INSERT INTO composer (first_name, last_name) VALUES ("Bjork","Gudmundsdottir");
INSERT INTO composer (first_name, last_name) VALUES ("","Blackburn");
INSERT INTO composer (first_name, last_name) VALUES ("Blind Lemon","Jefferson");
INSERT INTO composer (first_name, last_name) VALUES ("Bob","Bralove");
INSERT INTO composer (first_name, last_name) VALUES ("Bob","Brookmeyer");
INSERT INTO composer (first_name, last_name) VALUES ("Bob","Dorough");
INSERT INTO composer (first_name, last_name) VALUES ("Bob","Dylan");
INSERT INTO composer (first_name, last_name) VALUES ("Bob","Graettinger");
INSERT INTO composer (first_name, last_name) VALUES ("Bob","Johnson");
INSERT INTO composer (first_name, last_name) VALUES ("Bob","Mintzer");
INSERT INTO composer (first_name, last_name) VALUES ("Bob","Russell");
INSERT INTO composer (first_name, last_name) VALUES ("Bob","Thiele");
INSERT INTO composer (first_name, last_name) VALUES ("Bob","Weir");
INSERT INTO composer (first_name, last_name) VALUES ("Bobby","Haynes");
INSERT INTO composer (first_name, last_name) VALUES ("Bobby","Hebb");
INSERT INTO composer (first_name, last_name) VALUES ("Bobby","McFerrin");
INSERT INTO composer (first_name, last_name) VALUES ("Bobby","Watson");
INSERT INTO composer (first_name, last_name) VALUES ("Booker T.","Jones");
INSERT INTO composer (first_name, last_name) VALUES ("Booker T.","Washington");
INSERT INTO composer (first_name, last_name) VALUES ("Brad","Mehldau");
INSERT INTO composer (first_name, last_name) VALUES ("","Brammer");
INSERT INTO composer (first_name, last_name) VALUES ("Brandon","Flowers");
INSERT INTO composer (first_name, last_name) VALUES ("Brian","Wilson");
INSERT INTO composer (first_name, last_name) VALUES ("Brooks","Bowman");
INSERT INTO composer (first_name, last_name) VALUES ("","Brown");
INSERT INTO composer (first_name, last_name) VALUES ("Bruce","Cox");
INSERT INTO composer (first_name, last_name) VALUES ("Bruce","Foreman");
INSERT INTO composer (first_name, last_name) VALUES ("Bruce","Hornsby");
INSERT INTO composer (first_name, last_name) VALUES ("Bruce","Springsteen");
INSERT INTO composer (first_name, last_name) VALUES ("Buck","Clayton");
INSERT INTO composer (first_name, last_name) VALUES ("","Buckner");
INSERT INTO composer (first_name, last_name) VALUES ("Bud","Powell");
INSERT INTO composer (first_name, last_name) VALUES ("Buddy","Bernier");
INSERT INTO composer (first_name, last_name) VALUES ("C.","Sigman");
INSERT INTO composer (first_name, last_name) VALUES ("","Caesar");
INSERT INTO composer (first_name, last_name) VALUES ("Caetano","Veloso");
INSERT INTO composer (first_name, last_name) VALUES ("","Cahn");
INSERT INTO composer (first_name, last_name) VALUES ("Carl","Fisher");
INSERT INTO composer (first_name, last_name) VALUES ("Carl","Hampton");
INSERT INTO composer (first_name, last_name) VALUES ("Carl","Saunders");
INSERT INTO composer (first_name, last_name) VALUES ("Carlo","Ditta");
INSERT INTO composer (first_name, last_name) VALUES ("","Carmichael");
INSERT INTO composer (first_name, last_name) VALUES ("Carole Bayer","Sager");
INSERT INTO composer (first_name, last_name) VALUES ("Carpenter","Charles");
INSERT INTO composer (first_name, last_name) VALUES ("Carson","Smith");
INSERT INTO composer (first_name, last_name) VALUES ("Cary John","Franklin");
INSERT INTO composer (first_name, last_name) VALUES ("Charles","Bobbit");
INSERT INTO composer (first_name, last_name) VALUES ("Charles","Mitchell");
INSERT INTO composer (first_name, last_name) VALUES ("Charlie","Chaplin");
INSERT INTO composer (first_name, last_name) VALUES ("Charlie","Gabriel");
INSERT INTO composer (first_name, last_name) VALUES ("Charlie","Parker");
INSERT INTO composer (first_name, last_name) VALUES ("Chick","Corea");
INSERT INTO composer (first_name, last_name) VALUES ("Chick","Webb");
INSERT INTO composer (first_name, last_name) VALUES ("Chick","William Webb");
INSERT INTO composer (first_name, last_name) VALUES ("Chico","Buarque");
INSERT INTO composer (first_name, last_name) VALUES ("Chico","O'Farrill");
INSERT INTO composer (first_name, last_name) VALUES ("Chip","Young");
INSERT INTO composer (first_name, last_name) VALUES ("Chris","Curtain");
INSERT INTO composer (first_name, last_name) VALUES ("Chris","Potter");
INSERT INTO composer (first_name, last_name) VALUES ("Chris","Smither");
INSERT INTO composer (first_name, last_name) VALUES ("Chris","Stapleton");
INSERT INTO composer (first_name, last_name) VALUES ("Chris","Whitley");
INSERT INTO composer (first_name, last_name) VALUES ("Christopher R.","Squire");
INSERT INTO composer (first_name, last_name) VALUES ("Chuck","Darwin");
INSERT INTO composer (first_name, last_name) VALUES ("Chuck","Loeb");
INSERT INTO composer (first_name, last_name) VALUES ("Chuck","Rio");
INSERT INTO composer (first_name, last_name) VALUES ("Claude","Debussy");
INSERT INTO composer (first_name, last_name) VALUES ("Claudio","Monteverdi");
INSERT INTO composer (first_name, last_name) VALUES ("Claus","Ogerman");
INSERT INTO composer (first_name, last_name) VALUES ("Clifford","Brown");
INSERT INTO composer (first_name, last_name) VALUES ("Clint","Eastwood");
INSERT INTO composer (first_name, last_name) VALUES ("Clint","Houston");
INSERT INTO composer (first_name, last_name) VALUES ("Clint","Maedgen");
INSERT INTO composer (first_name, last_name) VALUES ("Kurt","Cobain");
INSERT INTO composer (first_name, last_name) VALUES ("Cole","Porter");
INSERT INTO composer (first_name, last_name) VALUES ("Colin","Greenwood");
INSERT INTO composer (first_name, last_name) VALUES ("Cootie","Williams");
INSERT INTO composer (first_name, last_name) VALUES ("","Coslow");
INSERT INTO composer (first_name, last_name) VALUES ("Courtney","Pine");
INSERT INTO composer (first_name, last_name) VALUES ("Curtis","Jones");
INSERT INTO composer (first_name, last_name) VALUES ("Cy","Coleman");
INSERT INTO composer (first_name, last_name) VALUES ("D.","Amy");
INSERT INTO composer (first_name, last_name) VALUES ("Dan","Wilson");
INSERT INTO composer (first_name, last_name) VALUES ("Dave","Bartholomew");
INSERT INTO composer (first_name, last_name) VALUES ("Dave","Holland");
INSERT INTO composer (first_name, last_name) VALUES ("Dave","Keuning");
INSERT INTO composer (first_name, last_name) VALUES ("David","Bowie");
INSERT INTO composer (first_name, last_name) VALUES ("David","Brubeck");
INSERT INTO composer (first_name, last_name) VALUES ("David","Gibson");
INSERT INTO composer (first_name, last_name) VALUES ("David","Lynch");
INSERT INTO composer (first_name, last_name) VALUES ("David","Mann");
INSERT INTO composer (first_name, last_name) VALUES ("David","Porter");
INSERT INTO composer (first_name, last_name) VALUES ("David","Torres");
INSERT INTO composer (first_name, last_name) VALUES ("","DeLange");
INSERT INTO composer (first_name, last_name) VALUES ("","DeSylva");
INSERT INTO composer (first_name, last_name) VALUES ("Deadric","Malone");
INSERT INTO composer (first_name, last_name) VALUES ("Declan","MacManus");
INSERT INTO composer (first_name, last_name) VALUES ("Dedette Lee","Hill");
INSERT INTO composer (first_name, last_name) VALUES ("Diana","Krall");
INSERT INTO composer (first_name, last_name) VALUES ("Diver","Artistes");
INSERT INTO composer (first_name, last_name) VALUES ("Dizzy","Gillespie");
INSERT INTO composer (first_name, last_name) VALUES ("Djalma","Ferreira");
INSERT INTO composer (first_name, last_name) VALUES ("","Djavan");
INSERT INTO composer (first_name, last_name) VALUES ("Don","Addrisi");
INSERT INTO composer (first_name, last_name) VALUES ("Don","George");
INSERT INTO composer (first_name, last_name) VALUES ("Donaldson","Kahn");
INSERT INTO composer (first_name, last_name) VALUES ("Dori","Caymmi");
INSERT INTO composer (first_name, last_name) VALUES ("Dorothy","Fields");
INSERT INTO composer (first_name, last_name) VALUES ("Dorothy","Parker");
INSERT INTO composer (first_name, last_name) VALUES ("DuBose","Heyward");
INSERT INTO composer (first_name, last_name) VALUES ("Duke","Ellington");
INSERT INTO composer (first_name, last_name) VALUES ("Duke","Pearson");
INSERT INTO composer (first_name, last_name) VALUES ("E. Y.","Harbourg");
INSERT INTO composer (first_name, last_name) VALUES ("Earl","King");
INSERT INTO composer (first_name, last_name) VALUES ("Eddie","Barclay");
INSERT INTO composer (first_name, last_name) VALUES ("Eddie","DeLange");
INSERT INTO composer (first_name, last_name) VALUES ("Eddy","DeLange");
INSERT INTO composer (first_name, last_name) VALUES ("Eden","Ahbez");
INSERT INTO composer (first_name, last_name) VALUES ("Edgar","Sampson");
INSERT INTO composer (first_name, last_name) VALUES ("Edgar Yip","Harburg");
INSERT INTO composer (first_name, last_name) VALUES ("Edie","Brickell");
INSERT INTO composer (first_name, last_name) VALUES ("Edu","Lobo");
INSERT INTO composer (first_name, last_name) VALUES ("Edward","Eliscu");
INSERT INTO composer (first_name, last_name) VALUES ("Edward","Heyman");
INSERT INTO composer (first_name, last_name) VALUES ("Edward Kennedy 'Duke'","Ellington");
INSERT INTO composer (first_name, last_name) VALUES ("Eliane","Elias");
INSERT INTO composer (first_name, last_name) VALUES ("Elthea","Peale");
INSERT INTO composer (first_name, last_name) VALUES ("Elvis","Costello");
INSERT INTO composer (first_name, last_name) VALUES ("Emilio","DeCavalieri");
INSERT INTO composer (first_name, last_name) VALUES ("Erich","Meder");
INSERT INTO composer (first_name, last_name) VALUES ("Erik","Satie");
INSERT INTO composer (first_name, last_name) VALUES ("Ernest Brooks 'Ernie'","Wilkins");
INSERT INTO composer (first_name, last_name) VALUES ("Ernie","Fields Jr.");
INSERT INTO composer (first_name, last_name) VALUES ("","Esperance");
INSERT INTO composer (first_name, last_name) VALUES ("","Evans");
INSERT INTO composer (first_name, last_name) VALUES ("EY","Harburg");
INSERT INTO composer (first_name, last_name) VALUES ("F.","Signorelli");
INSERT INTO composer (first_name, last_name) VALUES ("Fats","Domino");
INSERT INTO composer (first_name, last_name) VALUES ("Fats","Waller");
INSERT INTO composer (first_name, last_name) VALUES ("Felix","Bernard");
INSERT INTO composer (first_name, last_name) VALUES ("Ferdinand 'Jelly Roll'","Morton");
INSERT INTO composer (first_name, last_name) VALUES ("Fernando","Brant");
INSERT INTO composer (first_name, last_name) VALUES ("Fletcher","Henderson");
INSERT INTO composer (first_name, last_name) VALUES ("","Flouride");
INSERT INTO composer (first_name, last_name) VALUES ("Forest","Jackson Jr.");
INSERT INTO composer (first_name, last_name) VALUES ("Francisco","Torres");
INSERT INTO composer (first_name, last_name) VALUES ("Frank Benjamin","Foster");
INSERT INTO composer (first_name, last_name) VALUES ("Frank","Churchill");
INSERT INTO composer (first_name, last_name) VALUES ("Frank","Eyton");
INSERT INTO composer (first_name, last_name) VALUES ("Frank","Frost");
INSERT INTO composer (first_name, last_name) VALUES ("Frank","Mundy");
INSERT INTO composer (first_name, last_name) VALUES ("Frank","Paparelli");
INSERT INTO composer (first_name, last_name) VALUES ("Frank","Rosolino");
INSERT INTO composer (first_name, last_name) VALUES ("Frank Wellington","Wess");
INSERT INTO composer (first_name, last_name) VALUES ("Frankie","Laine");
INSERT INTO composer (first_name, last_name) VALUES ("Franklyn","Marks");
INSERT INTO composer (first_name, last_name) VALUES ("Franz","Lehar");
INSERT INTO composer (first_name, last_name) VALUES ("Franz","Liszt");
INSERT INTO composer (first_name, last_name) VALUES ("Fred","Coot");
INSERT INTO composer (first_name, last_name) VALUES ("Fred","Norman");
INSERT INTO composer (first_name, last_name) VALUES ("Fred","Wesley");
INSERT INTO composer (first_name, last_name) VALUES ("Freddie","Green");
INSERT INTO composer (first_name, last_name) VALUES ("Freddie","Hubbard");
INSERT INTO composer (first_name, last_name) VALUES ("Frederic","Chopin");
INSERT INTO composer (first_name, last_name) VALUES ("Frederick","Loewe");
INSERT INTO composer (first_name, last_name) VALUES ("G.","Geld");
INSERT INTO composer (first_name, last_name) VALUES ("G.","Shelley");
INSERT INTO composer (first_name, last_name) VALUES ("Gary","McFarland");
INSERT INTO composer (first_name, last_name) VALUES ("Gary","Peacock");
INSERT INTO composer (first_name, last_name) VALUES ("Gary","Winters");
INSERT INTO composer (first_name, last_name) VALUES ("Gaskill","McHugh");
INSERT INTO composer (first_name, last_name) VALUES ("Gene","Webster");
INSERT INTO composer (first_name, last_name) VALUES ("Geoffrey","Parsons");
INSERT INTO composer (first_name, last_name) VALUES ("George David","Weiss");
INSERT INTO composer (first_name, last_name) VALUES ("George","Douglas");
INSERT INTO composer (first_name, last_name) VALUES ("George Frideric","Handel");
INSERT INTO composer (first_name, last_name) VALUES ("George","Gershwin");
INSERT INTO composer (first_name, last_name) VALUES ("George","Harrison");
INSERT INTO composer (first_name, last_name) VALUES ("George","Jackson");
INSERT INTO composer (first_name, last_name) VALUES ("George","Martin");
INSERT INTO composer (first_name, last_name) VALUES ("George","Van Parys");
INSERT INTO composer (first_name, last_name) VALUES ("George","Whiting");
INSERT INTO composer (first_name, last_name) VALUES ("Georges","Auric");
INSERT INTO composer (first_name, last_name) VALUES ("Gerry","Mulligan");
INSERT INTO composer (first_name, last_name) VALUES ("Giacomo","Puccini");
INSERT INTO composer (first_name, last_name) VALUES ("Gigi","Gryce");
INSERT INTO composer (first_name, last_name) VALUES ("Gil","Evans");
INSERT INTO composer (first_name, last_name) VALUES ("Gilberto","Gil");
INSERT INTO composer (first_name, last_name) VALUES ("Gilles","Thibault");
INSERT INTO composer (first_name, last_name) VALUES ("Giovanni","Da Palestrina");
INSERT INTO composer (first_name, last_name) VALUES ("Giovanni","Palestrina");
INSERT INTO composer (first_name, last_name) VALUES ("Giulio","Caccini");
INSERT INTO composer (first_name, last_name) VALUES ("Gordon","Goodwin");
INSERT INTO composer (first_name, last_name) VALUES ("Gordon","Jenkins");
INSERT INTO composer (first_name, last_name) VALUES ("Graham","Massey");
INSERT INTO composer (first_name, last_name) VALUES ("Graham","Parker");
INSERT INTO composer (first_name, last_name) VALUES ("Graham","Williams");
INSERT INTO composer (first_name, last_name) VALUES ("Guy B.","Wood");
INSERT INTO composer (first_name, last_name) VALUES ("Hank","Mobley");
INSERT INTO composer (first_name, last_name) VALUES ("Hans","Lang");
INSERT INTO composer (first_name, last_name) VALUES ("Harold","Adamson");
INSERT INTO composer (first_name, last_name) VALUES ("Harold","Arlen");
INSERT INTO composer (first_name, last_name) VALUES ("Harold","Courlandar");
INSERT INTO composer (first_name, last_name) VALUES ("Harold","Land");
INSERT INTO composer (first_name, last_name) VALUES ("Harold","Mabern");
INSERT INTO composer (first_name, last_name) VALUES ("Harry","James");
INSERT INTO composer (first_name, last_name) VALUES ("Harry","Ruby");
INSERT INTO composer (first_name, last_name) VALUES ("Harry","Warren");
INSERT INTO composer (first_name, last_name) VALUES ("","Haydn");
INSERT INTO composer (first_name, last_name) VALUES ("Hector","Berlioz");
INSERT INTO composer (first_name, last_name) VALUES ("","Henderson");
INSERT INTO composer (first_name, last_name) VALUES ("Henri","Dutilleux");
INSERT INTO composer (first_name, last_name) VALUES ("Herb","Phillips");
INSERT INTO composer (first_name, last_name) VALUES ("Herbie","Hancock");
INSERT INTO composer (first_name, last_name) VALUES ("","Hewson");
INSERT INTO composer (first_name, last_name) VALUES ("Hoagy","Carmichael");
INSERT INTO composer (first_name, last_name) VALUES ("","Holland");
INSERT INTO composer (first_name, last_name) VALUES ("Homer","Banks");
INSERT INTO composer (first_name, last_name) VALUES ("Horace","Silver");
INSERT INTO composer (first_name, last_name) VALUES ("","Horton");
INSERT INTO composer (first_name, last_name) VALUES ("Howard","Dietz");
INSERT INTO composer (first_name, last_name) VALUES ("Hubert","Giraud");
INSERT INTO composer (first_name, last_name) VALUES ("Hubie","Wheeler");
INSERT INTO composer (first_name, last_name) VALUES ("Idrees","Sulieman");
INSERT INTO composer (first_name, last_name) VALUES ("Ike","Quebec");
INSERT INTO composer (first_name, last_name) VALUES ("Ira","Gershwin");
INSERT INTO composer (first_name, last_name) VALUES ("Irene","Kitchings");
INSERT INTO composer (first_name, last_name) VALUES ("Irving","Berlin");
INSERT INTO composer (first_name, last_name) VALUES ("Irving","Kahal");
INSERT INTO composer (first_name, last_name) VALUES ("Irving","Mills");
INSERT INTO composer (first_name, last_name) VALUES ("Isaac","Hayes");
INSERT INTO composer (first_name, last_name) VALUES ("Isham","Jones");
INSERT INTO composer (first_name, last_name) VALUES ("Ivan","Lins");
INSERT INTO composer (first_name, last_name) VALUES ("J.","Lytell");
INSERT INTO composer (first_name, last_name) VALUES ("J.","Marascalco");
INSERT INTO composer (first_name, last_name) VALUES ("J.","Young");
INSERT INTO composer (first_name, last_name) VALUES ("J.J.","Johnson");
INSERT INTO composer (first_name, last_name) VALUES ("Jack","DeJohnette");
INSERT INTO composer (first_name, last_name) VALUES ("Jack","King");
INSERT INTO composer (first_name, last_name) VALUES ("Jack","Lawrence");
INSERT INTO composer (first_name, last_name) VALUES ("Jack","Montrose");
INSERT INTO composer (first_name, last_name) VALUES ("Jacopo","Peri");
INSERT INTO composer (first_name, last_name) VALUES ("Jacques","Brel");
INSERT INTO composer (first_name, last_name) VALUES ("Jacques","Demy");
INSERT INTO composer (first_name, last_name) VALUES ("Jacques","Larue");
INSERT INTO composer (first_name, last_name) VALUES ("Jacques","Revaux");
INSERT INTO composer (first_name, last_name) VALUES ("","Jamal");
INSERT INTO composer (first_name, last_name) VALUES ("James","Hanley");
INSERT INTO composer (first_name, last_name) VALUES ("James","Heath");
INSERT INTO composer (first_name, last_name) VALUES ("James Oliver 'Trummy'","Young");
INSERT INTO composer (first_name, last_name) VALUES ("James R","Mundy");
INSERT INTO composer (first_name, last_name) VALUES ("James W Bubber","Miley");
INSERT INTO composer (first_name, last_name) VALUES ("Jamey","Aebersold");
INSERT INTO composer (first_name, last_name) VALUES ("Jaques Louis","Demy");
INSERT INTO composer (first_name, last_name) VALUES ("Jean 'Toots'","Thielemans");
INSERT INTO composer (first_name, last_name) VALUES ("Jean","Drejac");
INSERT INTO composer (first_name, last_name) VALUES ("Jeff","Lynne");
INSERT INTO composer (first_name, last_name) VALUES ("Jello","Biafra");
INSERT INTO composer (first_name, last_name) VALUES ("Jerome","Brainin");
INSERT INTO composer (first_name, last_name) VALUES ("Jerome","Kern");
INSERT INTO composer (first_name, last_name) VALUES ("Jerome","Moross");
INSERT INTO composer (first_name, last_name) VALUES ("Jerry","Garcia");
INSERT INTO composer (first_name, last_name) VALUES ("Jerry","Gladstone");
INSERT INTO composer (first_name, last_name) VALUES ("Jerry","Portnoy");
INSERT INTO composer (first_name, last_name) VALUES ("","Jets");
INSERT INTO composer (first_name, last_name) VALUES ("Jim","Hall");
INSERT INTO composer (first_name, last_name) VALUES ("Jimmie","Davis");
INSERT INTO composer (first_name, last_name) VALUES ("Jimmy","Bosch");
INSERT INTO composer (first_name, last_name) VALUES ("Jimmy","Forrest");
INSERT INTO composer (first_name, last_name) VALUES ("Jimmy","Heath");
INSERT INTO composer (first_name, last_name) VALUES ("Jimmy","Heusen");
INSERT INTO composer (first_name, last_name) VALUES ("Jimmy","McHugh");
INSERT INTO composer (first_name, last_name) VALUES ("Jimmy","Mundy");
INSERT INTO composer (first_name, last_name) VALUES ("Jimmy","Van Heusen");
INSERT INTO composer (first_name, last_name) VALUES ("Jimmy","Young");
INSERT INTO composer (first_name, last_name) VALUES ("Joe","Henderson");
INSERT INTO composer (first_name, last_name) VALUES ("Joe","Young");
INSERT INTO composer (first_name, last_name) VALUES ("Joe","Zawinul");
INSERT INTO composer (first_name, last_name) VALUES ("Joey","Tempest");
INSERT INTO composer (first_name, last_name) VALUES ("Johann Sebastian","Bach");
INSERT INTO composer (first_name, last_name) VALUES ("John","Blackburn");
INSERT INTO composer (first_name, last_name) VALUES ("John","Brooks");
INSERT INTO composer (first_name, last_name) VALUES ("John","Clayton");
INSERT INTO composer (first_name, last_name) VALUES ("John","Coltrane");
INSERT INTO composer (first_name, last_name) VALUES ("John","Dowland");
INSERT INTO composer (first_name, last_name) VALUES ("John","Dunstable");
INSERT INTO composer (first_name, last_name) VALUES ("John","Fogerty");
INSERT INTO composer (first_name, last_name) VALUES ("John","Green");
INSERT INTO composer (first_name, last_name) VALUES ("John","Greenwood");
INSERT INTO composer (first_name, last_name) VALUES ("John H.","Mercer");
INSERT INTO composer (first_name, last_name) VALUES ("John","Hall");
INSERT INTO composer (first_name, last_name) VALUES ("John","Hicks");
INSERT INTO composer (first_name, last_name) VALUES ("John","Hollenbeck");
INSERT INTO composer (first_name, last_name) VALUES ("John","Klenner");
INSERT INTO composer (first_name, last_name) VALUES ("John L.","Montgomery");
INSERT INTO composer (first_name, last_name) VALUES ("John","Latouche");
INSERT INTO composer (first_name, last_name) VALUES ("John","Lennon");
INSERT INTO composer (first_name, last_name) VALUES ("John","Lewis");
INSERT INTO composer (first_name, last_name) VALUES ("John","Mandel");
INSERT INTO composer (first_name, last_name) VALUES ("John P.","Murray");
INSERT INTO composer (first_name, last_name) VALUES ("John Roy","Anderson");
INSERT INTO composer (first_name, last_name) VALUES ("John","Turner");
INSERT INTO composer (first_name, last_name) VALUES ("Johnny","Burke");
INSERT INTO composer (first_name, last_name) VALUES ("Johnny","Cash");
INSERT INTO composer (first_name, last_name) VALUES ("Johnny","Green");
INSERT INTO composer (first_name, last_name) VALUES ("Johnny","Hodges");
INSERT INTO composer (first_name, last_name) VALUES ("Johnny","Mercer");
INSERT INTO composer (first_name, last_name) VALUES ("Johnny","Richards");
INSERT INTO composer (first_name, last_name) VALUES ("Jon","Anderson");
INSERT INTO composer (first_name, last_name) VALUES ("Joni","Mitchell");
INSERT INTO composer (first_name, last_name) VALUES ("Josef","Myrow");
INSERT INTO composer (first_name, last_name) VALUES ("Joseph Allan","McCarthy");
INSERT INTO composer (first_name, last_name) VALUES ("Joseph Dwight 'Joe'","Newman");
INSERT INTO composer (first_name, last_name) VALUES ("Joseph","Kosma");
INSERT INTO composer (first_name, last_name) VALUES ("Josquin","Desprez");
INSERT INTO composer (first_name, last_name) VALUES ("Juanito","Marquez");
INSERT INTO composer (first_name, last_name) VALUES ("Jule","Styne");
INSERT INTO composer (first_name, last_name) VALUES ("Jules","Massenet");
INSERT INTO composer (first_name, last_name) VALUES ("Karl","Suessdorf");
INSERT INTO composer (first_name, last_name) VALUES ("Kay","Swift");
INSERT INTO composer (first_name, last_name) VALUES ("Keith","Jarrett");
INSERT INTO composer (first_name, last_name) VALUES ("Keith","Richards");
INSERT INTO composer (first_name, last_name) VALUES ("Kelis","");
INSERT INTO composer (first_name, last_name) VALUES ("Kenny","Burrell");
INSERT INTO composer (first_name, last_name) VALUES ("Kenny","Clarke");
INSERT INTO composer (first_name, last_name) VALUES ("Kenny","Dorham");
INSERT INTO composer (first_name, last_name) VALUES ("Kenny","Garrett");
INSERT INTO composer (first_name, last_name) VALUES ("Kenny","Werner");
INSERT INTO composer (first_name, last_name) VALUES ("Kim","Gannon");
INSERT INTO composer (first_name, last_name) VALUES ("Kimati","Dinizulu");
INSERT INTO composer (first_name, last_name) VALUES ("Kurt","Elling");
INSERT INTO composer (first_name, last_name) VALUES ("Kurt","Weill");
INSERT INTO composer (first_name, last_name) VALUES ("Larry","Addison");
INSERT INTO composer (first_name, last_name) VALUES ("Larry","Douglas");
INSERT INTO composer (first_name, last_name) VALUES ("Larry","LaLonde");
INSERT INTO composer (first_name, last_name) VALUES ("Larry","Morey");
INSERT INTO composer (first_name, last_name) VALUES ("Larry","Willis");
INSERT INTO composer (first_name, last_name) VALUES ("Lars","Trier");
INSERT INTO composer (first_name, last_name) VALUES ("Laurence","Hobgood");
INSERT INTO composer (first_name, last_name) VALUES ("Laurindo","Almeida");
INSERT INTO composer (first_name, last_name) VALUES ("Lee","Gaines");
INSERT INTO composer (first_name, last_name) VALUES ("Leigh","Harline");
INSERT INTO composer (first_name, last_name) VALUES ("Leo","Robin");
INSERT INTO composer (first_name, last_name) VALUES ("Leonard","Bernstein");
INSERT INTO composer (first_name, last_name) VALUES ("Leonard","Feather");
INSERT INTO composer (first_name, last_name) VALUES ("Leonello","Casucci");
INSERT INTO composer (first_name, last_name) VALUES ("","Lerner");
INSERT INTO composer (first_name, last_name) VALUES ("","Loewe");
INSERT INTO composer (first_name, last_name) VALUES ("Les","Claypool");
INSERT INTO composer (first_name, last_name) VALUES ("Leslie","Bricusse");
INSERT INTO composer (first_name, last_name) VALUES ("Lester","Young");
INSERT INTO composer (first_name, last_name) VALUES ("","Lewis");
INSERT INTO composer (first_name, last_name) VALUES ("Lewis C.","Simpkins");
INSERT INTO composer (first_name, last_name) VALUES ("Linda","Thompson");
INSERT INTO composer (first_name, last_name) VALUES ("Loonis","McGlohon");
INSERT INTO composer (first_name, last_name) VALUES ("Lorenz","Hart");
INSERT INTO composer (first_name, last_name) VALUES ("Louis","Armstrong");
INSERT INTO composer (first_name, last_name) VALUES ("Ludacris","");
INSERT INTO composer (first_name, last_name) VALUES ("Ludwig Van","Beethoven");
INSERT INTO composer (first_name, last_name) VALUES ("Luiz","Antonio");
INSERT INTO composer (first_name, last_name) VALUES ("Lyle","Mays");
INSERT INTO composer (first_name, last_name) VALUES ("M.","Parris");
INSERT INTO composer (first_name, last_name) VALUES ("Mack","David");
INSERT INTO composer (first_name, last_name) VALUES ("Mack","Gordon");
INSERT INTO composer (first_name, last_name) VALUES ("Madonna","");
INSERT INTO composer (first_name, last_name) VALUES ("Manning","Sherwin");
INSERT INTO composer (first_name, last_name) VALUES ("Manny","Albem");
INSERT INTO composer (first_name, last_name) VALUES ("Marilyn","Manson");
INSERT INTO composer (first_name, last_name) VALUES ("Marcel","Mouloudji");
INSERT INTO composer (first_name, last_name) VALUES ("Marguerite","Monnot");
INSERT INTO composer (first_name, last_name) VALUES ("Maria","Schneider");
INSERT INTO composer (first_name, last_name) VALUES ("Marian","McPartland");
INSERT INTO composer (first_name, last_name) VALUES ("Marilyn","Bergman");
INSERT INTO composer (first_name, last_name) VALUES ("Marilyn","King");
INSERT INTO composer (first_name, last_name) VALUES ("Mark","Bell");
INSERT INTO composer (first_name, last_name) VALUES ("Mark","Stoermer");
INSERT INTO composer (first_name, last_name) VALUES ("","Marks");
INSERT INTO composer (first_name, last_name) VALUES ("Marty","Symes");
INSERT INTO composer (first_name, last_name) VALUES ("Mat","Mathews");
INSERT INTO composer (first_name, last_name) VALUES ("Matt","Dennis");
INSERT INTO composer (first_name, last_name) VALUES ("Maurice","Ravel");
INSERT INTO composer (first_name, last_name) VALUES ("Max","Roach");
INSERT INTO composer (first_name, last_name) VALUES ("Max","Seigel");
INSERT INTO composer (first_name, last_name) VALUES ("McCoy","Tyner");
INSERT INTO composer (first_name, last_name) VALUES ("McKinley","Morganfield");
INSERT INTO composer (first_name, last_name) VALUES ("Michael","Brecker");
INSERT INTO composer (first_name, last_name) VALUES ("Michael","Davis");
INSERT INTO composer (first_name, last_name) VALUES ("Michael","Franks");
INSERT INTO composer (first_name, last_name) VALUES ("Michael","Jackson");
INSERT INTO composer (first_name, last_name) VALUES ("Michael","Mondesir");
INSERT INTO composer (first_name, last_name) VALUES ("Michel","Legrand");
INSERT INTO composer (first_name, last_name) VALUES ("Mick","Jagger");
INSERT INTO composer (first_name, last_name) VALUES ("Miles","Davis");
INSERT INTO composer (first_name, last_name) VALUES ("Milt","Jackson");
INSERT INTO composer (first_name, last_name) VALUES ("Milton","Campbell");
INSERT INTO composer (first_name, last_name) VALUES ("Milton","Nascimento");
INSERT INTO composer (first_name, last_name) VALUES ("Modest","Mussorgsky");
INSERT INTO composer (first_name, last_name) VALUES ("Moe","Koffman");
INSERT INTO composer (first_name, last_name) VALUES ("Monty","Alexander");
INSERT INTO composer (first_name, last_name) VALUES ("Morton","Gould");
INSERT INTO composer (first_name, last_name) VALUES ("Mose","Allison");
INSERT INTO composer (first_name, last_name) VALUES ("","Mozart");
INSERT INTO composer (first_name, last_name) VALUES ("","Mullen");
INSERT INTO composer (first_name, last_name) VALUES ("","Mulligan");
INSERT INTO composer (first_name, last_name) VALUES ("Murray","Berlin");
INSERT INTO composer (first_name, last_name) VALUES ("Nacio Herb","Brown");
INSERT INTO composer (first_name, last_name) VALUES ("Nate","Smith");
INSERT INTO composer (first_name, last_name) VALUES ("Neal","Hefti");
INSERT INTO composer (first_name, last_name) VALUES ("Ned","Washington");
INSERT INTO composer (first_name, last_name) VALUES ("Nena","");
INSERT INTO composer (first_name, last_name) VALUES ("Ney","Mcall");
INSERT INTO composer (first_name, last_name) VALUES ("Nick","Gravenites");
INSERT INTO composer (first_name, last_name) VALUES ("Nick","Lowe");
INSERT INTO composer (first_name, last_name) VALUES ("Norman J.","Simon");
INSERT INTO composer (first_name, last_name) VALUES ("Norman","Span");
INSERT INTO composer (first_name, last_name) VALUES ("Onaje Allan ","umbs");
INSERT INTO composer (first_name, last_name) VALUES ("Orlando","Di Lasso");
INSERT INTO composer (first_name, last_name) VALUES ("Oscar","Castro-Neves");
INSERT INTO composer (first_name, last_name) VALUES ("Oscar","Hammerstein II");
INSERT INTO composer (first_name, last_name) VALUES ("Oscar","Peterson");
INSERT INTO composer (first_name, last_name) VALUES ("Oscar","Washington");
INSERT INTO composer (first_name, last_name) VALUES ("Otto A.","Harbach");
INSERT INTO composer (first_name, last_name) VALUES ("P","King");
INSERT INTO composer (first_name, last_name) VALUES ("P.","Udell");
INSERT INTO composer (first_name, last_name) VALUES ("Pat","Metheny");
INSERT INTO composer (first_name, last_name) VALUES ("Paul","Denniker");
INSERT INTO composer (first_name, last_name) VALUES ("Paul","Francis Webster");
INSERT INTO composer (first_name, last_name) VALUES ("Paul","James");
INSERT INTO composer (first_name, last_name) VALUES ("Paul","McCartney");
INSERT INTO composer (first_name, last_name) VALUES ("Paul","Williams");
INSERT INTO composer (first_name, last_name) VALUES ("Paulette","Girard");
INSERT INTO composer (first_name, last_name) VALUES ("Paulo","Emilio");
INSERT INTO composer (first_name, last_name) VALUES ("Percy","Mayfield");
INSERT INTO composer (first_name, last_name) VALUES ("Pete","Rugolo");
INSERT INTO composer (first_name, last_name) VALUES ("Peter","Giftos");
INSERT INTO composer (first_name, last_name) VALUES ("Peter Ilyich","Tchaikovsky");
INSERT INTO composer (first_name, last_name) VALUES ("Peter","Rose");
INSERT INTO composer (first_name, last_name) VALUES ("Philippe","Catherine");
INSERT INTO composer (first_name, last_name) VALUES ("Phillip","Braham");
INSERT INTO composer (first_name, last_name) VALUES ("Pierre","Attaingnant");
INSERT INTO composer (first_name, last_name) VALUES ("Poncho","Sanchez");
INSERT INTO composer (first_name, last_name) VALUES ("Rahsaan Roland","Kirk");
INSERT INTO composer (first_name, last_name) VALUES ("Ray","Brown");
INSERT INTO composer (first_name, last_name) VALUES ("Ray","Noble");
INSERT INTO composer (first_name, last_name) VALUES ("Raye-De","Paul");
INSERT INTO composer (first_name, last_name) VALUES ("Redd","Evans");;
INSERT INTO composer (first_name, last_name) VALUES ("Reggie","Ward");
INSERT INTO composer (first_name, last_name) VALUES ("Rene","Touzet");
INSERT INTO composer (first_name, last_name) VALUES ("Rentaro","Taki");
INSERT INTO composer (first_name, last_name) VALUES ("Reverend","Raven");
INSERT INTO composer (first_name, last_name) VALUES ("Richard","Addrisi");
INSERT INTO composer (first_name, last_name) VALUES ("Richard B.","Smith");
INSERT INTO composer (first_name, last_name) VALUES ("Richard Charles","Rodgers");
INSERT INTO composer (first_name, last_name) VALUES ("Richard Dean","Powell");
INSERT INTO composer (first_name, last_name) VALUES ("Richard","Kuebler");
INSERT INTO composer (first_name, last_name) VALUES ("Richard","Rodgers");
INSERT INTO composer (first_name, last_name) VALUES ("Richie","Beirach");
INSERT INTO composer (first_name, last_name) VALUES ("Rickie","Monie");
INSERT INTO composer (first_name, last_name) VALUES ("Rob","Garza");
INSERT INTO composer (first_name, last_name) VALUES ("Eric","Hilton");
INSERT INTO composer (first_name, last_name) VALUES ("Rob","Wasserman");
INSERT INTO composer (first_name, last_name) VALUES ("Robert","Brookmeyer");
INSERT INTO composer (first_name, last_name) VALUES ("Robert","Hunter");
INSERT INTO composer (first_name, last_name) VALUES ("Robert","Mellin");
INSERT INTO composer (first_name, last_name) VALUES ("Robert","Schumann");
INSERT INTO composer (first_name, last_name) VALUES ("Robert","Sour");
INSERT INTO composer (first_name, last_name) VALUES ("Robert","Taylor");
INSERT INTO composer (first_name, last_name) VALUES ("Robin","Eubanks");
INSERT INTO composer (first_name, last_name) VALUES ("Ronnie","Vannucci");
INSERT INTO composer (first_name, last_name) VALUES ("Roy","Alfred");
INSERT INTO composer (first_name, last_name) VALUES ("Roy","Hargrove");
INSERT INTO composer (first_name, last_name) VALUES ("Roy","Hayes");
INSERT INTO composer (first_name, last_name) VALUES ("","Ruskin");
INSERT INTO composer (first_name, last_name) VALUES ("Russell","Ferrante");
INSERT INTO composer (first_name, last_name) VALUES ("Ruth","Roberts");
INSERT INTO composer (first_name, last_name) VALUES ("S.","Romberg");
INSERT INTO composer (first_name, last_name) VALUES ("S.K.","Russell");
INSERT INTO composer (first_name, last_name) VALUES ("","Salieri");
INSERT INTO composer (first_name, last_name) VALUES ("Sam","Coslow");
INSERT INTO composer (first_name, last_name) VALUES ("Sam","McClain");
INSERT INTO composer (first_name, last_name) VALUES ("Sam","Mosley");
INSERT INTO composer (first_name, last_name) VALUES ("Sam","Phillips");
INSERT INTO composer (first_name, last_name) VALUES ("Sammy","Cahn");
INSERT INTO composer (first_name, last_name) VALUES ("Sammy","Fain");
INSERT INTO composer (first_name, last_name) VALUES ("Sammy","Gallop");
INSERT INTO composer (first_name, last_name) VALUES ("Samuel A.","Ward");
INSERT INTO composer (first_name, last_name) VALUES ("Samuel","Lewis");
INSERT INTO composer (first_name, last_name) VALUES ("","Schubert");
INSERT INTO composer (first_name, last_name) VALUES ("","Schumann");
INSERT INTO composer (first_name, last_name) VALUES ("","Selway");
INSERT INTO composer (first_name, last_name) VALUES ("Shaddix","");
INSERT INTO composer (first_name, last_name) VALUES ("Shorty","Rogers");
INSERT INTO composer (first_name, last_name) VALUES ("Sigurjon Birgir","Sigurdsson");
INSERT INTO composer (first_name, last_name) VALUES ("","Simons");
INSERT INTO composer (first_name, last_name) VALUES ("","Slesinger");
INSERT INTO composer (first_name, last_name) VALUES ("Slide","Hampton");
INSERT INTO composer (first_name, last_name) VALUES ("","Smith");
INSERT INTO composer (first_name, last_name) VALUES ("Snoop","Doggy Dogg");
INSERT INTO composer (first_name, last_name) VALUES ("Sofia","Gubaidulina");
INSERT INTO composer (first_name, last_name) VALUES ("Sol","Lake");
INSERT INTO composer (first_name, last_name) VALUES ("Sonny","Henry");
INSERT INTO composer (first_name, last_name) VALUES ("Sonny","Rollins");
INSERT INTO composer (first_name, last_name) VALUES ("Stan","Freeman");
INSERT INTO composer (first_name, last_name) VALUES ("Stan","Kenton");
INSERT INTO composer (first_name, last_name) VALUES ("Steve","Howe");
INSERT INTO composer (first_name, last_name) VALUES ("Steve","Nelson");
INSERT INTO composer (first_name, last_name) VALUES ("Steve","Swallow");
INSERT INTO composer (first_name, last_name) VALUES ("Steve","Turre");
INSERT INTO composer (first_name, last_name) VALUES ("Stevie","Wonder");
INSERT INTO composer (first_name, last_name) VALUES ("","Styne");
INSERT INTO composer (first_name, last_name) VALUES ("","Suesdorff");
INSERT INTO composer (first_name, last_name) VALUES ("","Sullivan");
INSERT INTO composer (first_name, last_name) VALUES ("Sy","Oliver");
INSERT INTO composer (first_name, last_name) VALUES ("T.","Boyce");
INSERT INTO composer (first_name, last_name) VALUES ("Tadd","Dameron");
INSERT INTO composer (first_name, last_name) VALUES ("Ted","Koehler");
INSERT INTO composer (first_name, last_name) VALUES ("Terrell","Kirk");
INSERT INTO composer (first_name, last_name) VALUES ("Terry","Holmes");
INSERT INTO composer (first_name, last_name) VALUES ("Terry","Tate");
INSERT INTO composer (first_name, last_name) VALUES ("Thad","Jones");
INSERT INTO composer (first_name, last_name) VALUES ("Thelonious","Monk");
INSERT INTO composer (first_name, last_name) VALUES ("Thomas 'Fats'","Waller");
INSERT INTO composer (first_name, last_name) VALUES ("Thomas","Weelkes");
INSERT INTO composer (first_name, last_name) VALUES ("Thomas Wright","Waller");
INSERT INTO composer (first_name, last_name) VALUES ("Tim","Alexander");
INSERT INTO composer (first_name, last_name) VALUES ("Tito","Puente");
INSERT INTO composer (first_name, last_name) VALUES ("Tom","Adair");
INSERT INTO composer (first_name, last_name) VALUES ("Tom","Waits");
INSERT INTO composer (first_name, last_name) VALUES ("Toma¡s Luis","De Victoria");
INSERT INTO composer (first_name, last_name) VALUES ("Toshiko","Akiyoshi");
INSERT INTO composer (first_name, last_name) VALUES ("Tracy Louise","Spencer");
INSERT INTO composer (first_name, last_name) VALUES ("Trent","Reznor");
INSERT INTO composer (first_name, last_name) VALUES ("Trevor","Horn");
INSERT INTO composer (first_name, last_name) VALUES ("Trevor","Rabin");
INSERT INTO composer (first_name, last_name) VALUES ("Turner","Johnson");
INSERT INTO composer (first_name, last_name) VALUES ("Ulf","Wakenius");
INSERT INTO composer (first_name, last_name) VALUES ("Van","Heusen");
INSERT INTO composer (first_name, last_name) VALUES ("","Verdi");
INSERT INTO composer (first_name, last_name) VALUES ("Vernon","Duke");
INSERT INTO composer (first_name, last_name) VALUES ("Victor","Lewis");
INSERT INTO composer (first_name, last_name) VALUES ("Victor","Schertzinger");
INSERT INTO composer (first_name, last_name) VALUES ("Victor","Wesley");
INSERT INTO composer (first_name, last_name) VALUES ("Victor","Young");
INSERT INTO composer (first_name, last_name) VALUES ("Vince","Welnick");
INSERT INTO composer (first_name, last_name) VALUES ("Vincent Millie","Youmans");
INSERT INTO composer (first_name, last_name) VALUES ("Vitor","Martins");
INSERT INTO composer (first_name, last_name) VALUES ("","Wagner");
INSERT INTO composer (first_name, last_name) VALUES ("Walter","Donaldson");
INSERT INTO composer (first_name, last_name) VALUES ("Walter","Gross");
INSERT INTO composer (first_name, last_name) VALUES ("","Washington");
INSERT INTO composer (first_name, last_name) VALUES ("Wayne","Shorter");
INSERT INTO composer (first_name, last_name) VALUES ("Wes","Montgomery");
INSERT INTO composer (first_name, last_name) VALUES ("Willard","Robinson");
INSERT INTO composer (first_name, last_name) VALUES ("William 'Count'","Basie");
INSERT INTO composer (first_name, last_name) VALUES ("William","Byrd");
INSERT INTO composer (first_name, last_name) VALUES ("William","Cornysh");
INSERT INTO composer (first_name, last_name) VALUES ("William","Eaton");
INSERT INTO composer (first_name, last_name) VALUES ("William","Katz");
INSERT INTO composer (first_name, last_name) VALUES ("Willie","Dixon");
INSERT INTO composer (first_name, last_name) VALUES ("Wolfgang Amadeus","Mozart");
INSERT INTO composer (first_name, last_name) VALUES ("Woody","Shaw");
INSERT INTO composer (first_name, last_name) VALUES ("","Youmans");
