INSERT INTO genre (description) VALUES ("Alternative");
INSERT INTO genre (description) VALUES ("Alternative & Punk");
INSERT INTO genre (description) VALUES ("Blues");
INSERT INTO genre (description) VALUES ("Classical");
INSERT INTO genre (description) VALUES ("Electronica");
INSERT INTO genre (description) VALUES ("Electronica/Dance");
INSERT INTO genre (description) VALUES ("General/Unclassifiable");
INSERT INTO genre (description) VALUES ("Hip Hop/Rap");
INSERT INTO genre (description) VALUES ("Indie Rock");
INSERT INTO genre (description) VALUES ("Jazz");
INSERT INTO genre (description) VALUES ("Latin");
INSERT INTO genre (description) VALUES ("Other");
INSERT INTO genre (description) VALUES ("Pop");
INSERT INTO genre (description) VALUES ("R&B");
INSERT INTO genre (description) VALUES ("Rock");
INSERT INTO genre (description) VALUES ("Singer/Songwriter");
INSERT INTO genre (description) VALUES ("Soundtrack");
INSERT INTO genre (description) VALUES ("Spoken & Audio");
INSERT INTO genre (description) VALUES ("Traditional");
